-- CreateTable
CREATE TABLE "WebWhatsapp" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "clientId" STRING NOT NULL,
    "session" STRING NOT NULL,

    CONSTRAINT "WebWhatsapp_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "WebWhatsapp_clientId_key" ON "WebWhatsapp"("clientId");
